In [2]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
b = np.array([[1, 2, 3],[5, 6, 7]])
b

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
# dimensao do Array
b.ndim

2

In [16]:
b.shape

(2, 3)

In [17]:
len(b)

2

In [22]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
d = np.arange(0,101,1)
print(d)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [26]:
e = np.arange(20,10, -1)
e

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [27]:
#Primeiro valor = inicio, segundo valor = final, terceiro valor = quantidade de número entre o primeiro e segundo valor.
f = np.linspace(1, 10, 10)
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
g = np.linspace(1, 10, 20)
g

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [47]:
h = np.arange(0, 6)
i = np.array([[0, 1, 2, 3, 4, 5],[1, 2, 3, 4, 5,6],[2, 3, 4, 5, 6, 7] ])
print(h)
print()
print(i)

[0 1 2 3 4 5]

[[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]]


In [49]:
j = np.ones(10)
j

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
k = np.ones((5, 5))
print(k)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
l = np.zeros((5, 5))
print(l)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [55]:
#Números aleatorios de 0 a 1 
m = np.random.rand(10)
m

array([0.94751569, 0.29849031, 0.13125708, 0.55829835, 0.2349221 ,
       0.02390621, 0.78002025, 0.70406243, 0.8324213 , 0.41067815])

In [106]:
n = np.random.randint(100)
print(n)

51
